" don't bother with vi compatibility
set nocompatible

" enable syntax highlighting
syntax enable

" configure Vundle
filetype on " without this vim emits a zero exit status, later, because of :ft off
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'airblade/vim-gitgutter'
Plugin 'scrooloose/nerdtree'
Plugin 'morhetz/gruvbox'
Plugin 'vim-airline/vim-airline'

call vundle#end()

" ensure ftdetect et al work by including this after the Vundle stuff
filetype plugin indent on

set linespace=2                                              "字符间插入的像素行数目
set autoindent                                               "自动缩进
set autoread                                                 "当文件被改动时自动载入
set backspace=2                                              "使backspace正常处理indent, eol, start等
set backupcopy=yes                                           "备份时覆盖
set clipboard=unnamed                                        "系统剪贴板
set directory-=.                                             "不在当前文件夹保存swap文件
set encoding=utf-8                                           "编码
set ignorecase                                               "搜索忽略大小写
set incsearch                                                "即时看到查找结果
set hlsearch                                                 "搜索关键字高亮显示
set laststatus=2                                             "显示状态栏
set list                                                     "显示tab键
set listchars=tab:▸\ ,trail:◆
set number                                                   "显示行号
set ruler                                                    "显示位置
set scrolloff=3                                              "上下有几行
set shiftwidth=4
set showcmd
set showmode
set smartcase
set softtabstop=2
set tabstop=8
set cursorline                                               "突出显示当前行
set mouse=a                                                  "可以在buffer的任何地方使用鼠标

" keyboard shortcuts
let mapleader = ','
noremap <C-h> <C-w>h
noremap <C-j> <C-w>j
noremap <C-k> <C-w>k
noremap <C-l> <C-w>l
nnoremap <leader>d :NERDTreeToggle<CR>
nnoremap <leader>f :NERDTreeFind<CR>

" plugin settings
let g:NERDSpaceDelims=1
let g:gitgutter_enabled = 1
let g:gruvbox_bold = 0

colorscheme gruvbox
